"use client"
import { useState } from 'react'
import { OnboardingState, SevenSins, STEP_NAMES } from '@/types/onboarding'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { FileText, Target, Users, MessageCircle, BarChart3, Zap, CheckCircle2, Download, Loader2, Sparkles, Image, Video, Music, Mic } from 'lucide-react'
import { generateStrategyBriefHTML } from '@/lib/generate-pdf'
import type { CreativeResult, CampaignContext } from '@/lib/creative/types'

interface Props {
  state: OnboardingState
  update: (v: Partial<OnboardingState['presentation']>) => void
}

const SIN_LABELS: Record<SevenSins, string> = {
  greed: 'Greed', pride: 'Pride', envy: 'Envy', lust: 'Desire',
  wrath: 'Frustration', sloth: 'Ease', gluttony: 'Abundance'
}

const GOAL_LABELS: Record<string, string> = {
  hire: 'Recruit / Hire', sales: 'Close Sales', leads: 'Generate Leads',
  revenue: 'Grow Revenue', signups: 'Get Signups', brand: 'Build Brand',
}
const TIMELINE_LABELS: Record<string, string> = {
  '1_week': 'This week', '2_weeks': 'Next 2 weeks', '1_month': 'This month',
  '3_months': 'Next quarter', '6_months': '6 months', '1_year': 'This year',
}
const BUDGET_LABELS: Record<string, string> = {
  under_500: 'Under $500/mo', '500_2k': '$500 – $2,000/mo', '2k_5k': '$2,000 – $5,000/mo',
  '5k_10k': '$5,000 – $10,000/mo', '10k_plus': '$10,000+/mo', unsure: 'Not sure yet',
}

function fmt(map: Record<string, string>, val: string | undefined) {
  if (!val) return '—'
  return map[val] || val.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}

export function StepPresentation({ state, update }: Props) {
  const [isGenerating, setIsGenerating] = useState(false)
  const activeTriggers = state.messaging.emotional_triggers.filter(t => t.intensity > 5)
  const personas = [...(state.personas.current || []), ...(state.personas.ideal || [])]
  const allocatedChannels = Object.entries(state.strategy.budget_split || {}).filter(([, v]) => v > 0)

  const handleDownloadPDF = () => {
    setIsGenerating(true)
    try {
      const html = generateStrategyBriefHTML(state)
      const blob = new Blob([html], { type: 'text/html' })
      const url = URL.createObjectURL(blob)
      const win = window.open(url, '_blank')
      if (win) {
        // The opened page has a "Download as PDF" button that triggers print dialog
        update({ pdf_url: 'generated' })
      }
    } catch (e) {
      console.error('PDF generation failed:', e)
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Strategy document header */}
      <div className="rounded-2xl border bg-card overflow-hidden">
        <div className="bg-primary/5 border-b px-6 py-5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center">
                <FileText className="w-5 h-5 text-primary-foreground" />
              </div>
              <div>
                <h2 className="font-bold text-lg">Strategy Brief</h2>
                <p className="text-xs text-muted-foreground">Generated by TorqueLoop AI</p>
              </div>
            </div>
            <Button
              onClick={handleDownloadPDF}
              disabled={isGenerating}
              size="sm"
              className="gap-1.5"
            >
              {isGenerating ? (
                <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating...</>
              ) : (
                <><Download className="w-3.5 h-3.5" /> Download PDF</>
              )}
            </Button>
          </div>
          <p className="text-sm text-muted-foreground mt-3">
            Review your complete marketing strategy below. After approval, TorqueLoop will begin
            generating creatives and setting up campaigns across your chosen channels.
          </p>
        </div>

        {/* Goals section */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <Target className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Goals & Parameters</h3>
          </div>
          <div className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
            <div>
              <span className="text-muted-foreground text-xs">Primary goal</span>
              <p className="font-medium">{fmt(GOAL_LABELS, state.goals.primary)}</p>
            </div>
            <div>
              <span className="text-muted-foreground text-xs">Timeline</span>
              <p className="font-medium">{fmt(TIMELINE_LABELS, state.goals.timeline)}</p>
            </div>
            <div>
              <span className="text-muted-foreground text-xs">Budget range</span>
              <p className="font-medium">{fmt(BUDGET_LABELS, state.goals.budget_range)}</p>
            </div>
            <div>
              <span className="text-muted-foreground text-xs">Tracking system</span>
              <p className="font-medium capitalize">{state.tracking.system ? state.tracking.system.replace(/_/g, ' ') : 'None'}</p>
            </div>
            {state.outcomes?.type && (
              <>
                <div>
                  <span className="text-muted-foreground text-xs">Outcome type</span>
                  <p className="font-medium capitalize">{state.outcomes.type === 'custom' ? state.outcomes.custom_label : state.outcomes.type.replace(/_/g, ' ')}</p>
                </div>
                {state.outcomes.target_per_month && (
                  <div>
                    <span className="text-muted-foreground text-xs">Target / month</span>
                    <p className="font-medium">{state.outcomes.target_per_month}</p>
                  </div>
                )}
              </>
            )}
          </div>
        </div>

        {/* Channel history */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <BarChart3 className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Channel History</h3>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {state.channels.worked.length > 0 && state.channels.worked.map(c => (
              <Badge key={`w-${c}`} variant="outline" className="text-xs border-green-500/30 text-green-700 bg-green-50">
                {c.replace(/_/g, ' ')} — worked
              </Badge>
            ))}
            {state.channels.failed.length > 0 && state.channels.failed.map(c => (
              <Badge key={`f-${c}`} variant="outline" className="text-xs border-red-500/30 text-red-700 bg-red-50">
                {c.replace(/_/g, ' ')} — didn't work
              </Badge>
            ))}
            {state.channels.used.filter(c => !state.channels.worked.includes(c) && !state.channels.failed.includes(c)).map(c => (
              <Badge key={`u-${c}`} variant="outline" className="text-xs">
                {c.replace(/_/g, ' ')} — tried
              </Badge>
            ))}
            {state.channels.used.length === 0 && (
              <span className="text-xs text-muted-foreground">No channel history provided</span>
            )}
          </div>
        </div>

        {/* Personas */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <Users className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Target Personas ({personas.length})</h3>
          </div>
          {personas.length === 0 ? (
            <span className="text-xs text-muted-foreground">No personas defined — consider going back to add at least one.</span>
          ) : (
            <div className="space-y-2">
              {personas.map((p, i) => (
                <div key={`persona-${p.name || i}`} className="rounded-lg bg-muted/50 p-3">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className="font-medium text-sm">{p.name || `Persona ${i + 1}`}</span>
                    {p.age_range && <Badge variant="outline" className="text-[10px] px-1.5 py-0">{p.age_range}</Badge>}
                    {p.location && <Badge variant="outline" className="text-[10px] px-1.5 py-0">{p.location}</Badge>}
                  </div>
                  {p.occupation && <div className="text-xs text-muted-foreground">{p.occupation}</div>}
                  {p.pain_points.length > 0 && (
                    <div className="text-xs mt-1">
                      <span className="text-muted-foreground">Pain points:</span>{' '}
                      {p.pain_points.join(', ')}
                    </div>
                  )}
                  {p.media_habits && p.media_habits.length > 0 && (
                    <div className="text-xs mt-1">
                      <span className="text-muted-foreground">Media:</span>{' '}
                      {p.media_habits.join(', ')}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Messaging strategy */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <MessageCircle className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Messaging Strategy</h3>
          </div>
          <div className="mb-2">
            <span className="text-xs text-muted-foreground">Brand tone:</span>{' '}
            <span className="text-sm font-medium capitalize">{state.messaging.tone || 'Not set'}</span>
          </div>
          {activeTriggers.length > 0 ? (
            <div className="space-y-1.5">
              {activeTriggers.map(t => (
                <div key={t.sin} className="flex items-start gap-2 text-sm">
                  <Badge variant="outline" className="text-[10px] px-1.5 py-0 shrink-0 mt-0.5">
                    {SIN_LABELS[t.sin]} ({t.intensity}/10)
                  </Badge>
                  <span className="text-muted-foreground text-xs">{t.message || 'No message set'}</span>
                </div>
              ))}
            </div>
          ) : (
            <span className="text-xs text-muted-foreground">No active emotional triggers</span>
          )}
        </div>

        {/* Channel strategy */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <Zap className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Channel Strategy</h3>
          </div>
          <div className="mb-2 text-sm">
            <span className="text-muted-foreground text-xs">Organic / Paid split:</span>{' '}
            <span className="font-medium">{state.strategy.organic_vs_paid}% organic / {100 - state.strategy.organic_vs_paid}% paid</span>
          </div>
          {allocatedChannels.length > 0 ? (
            <div className="space-y-1">
              {allocatedChannels
                .sort((a, b) => b[1] - a[1])
                .map(([ch, pct]) => (
                  <div key={ch} className="flex items-center gap-2">
                    <div className="flex-1 text-sm capitalize">{ch.replace(/_/g, ' ')}</div>
                    <div className="w-32 h-2 rounded-full bg-muted overflow-hidden">
                      <div
                        className="h-full bg-primary rounded-full transition-all"
                        style={{ width: `${pct * 2}%` }}
                      />
                    </div>
                    <span className="text-xs font-mono w-8 text-right">{pct}%</span>
                  </div>
                ))}
            </div>
          ) : (
            <span className="text-xs text-muted-foreground">No channels allocated yet</span>
          )}
        </div>

        {/* Completion checklist */}
        <div className="px-6 py-4">
          <div className="flex items-center gap-2 mb-3">
            <CheckCircle2 className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Readiness Checklist</h3>
          </div>
          <div className="space-y-1">
            {[
              { label: 'Goals defined', done: !!state.goals.primary },
              { label: 'Tracking selected', done: !!state.tracking.system },
              { label: 'Outcomes defined', done: !!state.outcomes?.type },
              { label: 'Channels audited', done: state.channels.used.length > 0 },
              { label: 'Personas created', done: personas.length > 0 },
              { label: 'Messaging crafted', done: activeTriggers.length > 0 },
              { label: 'Budget allocated', done: allocatedChannels.length > 0 },
            ].map(item => (
              <div key={item.label} className="flex items-center gap-2 text-sm">
                <div className={`w-4 h-4 rounded-full flex items-center justify-center ${
                  item.done ? 'bg-green-500 text-white' : 'bg-muted'
                }`}>
                  {item.done && <CheckCircle2 className="w-3 h-3" />}
                </div>
                <span className={item.done ? 'text-foreground' : 'text-muted-foreground'}>{item.label}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Creative Generation Panel */}
      <CreativeGenerationPanel state={state} />
    </div>
  )
}

// ── Creative Generation Panel ──
function CreativeGenerationPanel({ state }: { state: OnboardingState }) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [results, setResults] = useState<CreativeResult[]>([])
  const [error, setError] = useState<string | null>(null)
  const [providers, setProviders] = useState<string[]>([])
  const [totalCost, setTotalCost] = useState(0)

  const allocatedChannels = Object.entries(state.strategy.budget_split || {})
    .filter(([, v]) => v > 0)
    .map(([ch]) => ch)

  const buildCampaignContext = (): CampaignContext => ({
    business_name: 'Your Business',
    goal: state.goals.primary || 'growth',
    outcome_type: state.outcomes?.type || '',
    personas: [...(state.personas.current || []), ...(state.personas.ideal || [])].map(p => ({
      name: p.name || 'Target Customer',
      age_range: p.age_range || '25-45',
      location: p.location || '',
      pain_points: p.pain_points || [],
      media_habits: p.media_habits || [],
    })),
    tone: state.messaging.tone || 'professional',
    emotional_triggers: (state.messaging.emotional_triggers || [])
      .filter(t => t.intensity > 5)
      .map(t => ({ sin: t.sin, message: t.message, intensity: t.intensity })),
    channels: allocatedChannels,
    budget_range: state.goals.budget_range || 'unsure',
  })

  const handleGenerate = async (mode: 'preview' | 'full') => {
    setIsGenerating(true)
    setError(null)

    try {
      const campaign = buildCampaignContext()
      const response = await fetch('/api/creative/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          campaign,
          mode,
          language: 'en',
          maxGenerations: mode === 'preview' ? 3 : 15,
          channel: mode === 'preview' ? allocatedChannels[0] : undefined,
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        setError(data.error || 'Creative generation failed')
        return
      }

      if (mode === 'preview' && data.result) {
        setResults([data.result])
      } else if (data.results) {
        setResults(data.results)
      }

      setProviders(data.providers_available || data.providers_used || [])
      setTotalCost(data.total_cost_usd || 0)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Network error')
    } finally {
      setIsGenerating(false)
    }
  }

  const readyResults = results.filter(r => r.status === 'ready')
  const failedResults = results.filter(r => r.status === 'failed')

  const ASSET_ICONS: Record<string, React.ReactNode> = {
    static: <Image className="w-3.5 h-3.5" />,
    video: <Video className="w-3.5 h-3.5" />,
    audio_jingle: <Music className="w-3.5 h-3.5" />,
    audio_voiceover: <Mic className="w-3.5 h-3.5" />,
    audio_instrumental: <Music className="w-3.5 h-3.5" />,
  }

  return (
    <div className="rounded-2xl border bg-card overflow-hidden">
      <div className="bg-gradient-to-r from-violet-500/10 to-blue-500/10 border-b px-6 py-5">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-blue-500 flex items-center justify-center">
            <Sparkles className="w-5 h-5 text-white" />
          </div>
          <div>
            <h2 className="font-bold text-lg">Creative Engine</h2>
            <p className="text-xs text-muted-foreground">AI-powered ad creative generation</p>
          </div>
        </div>
        <p className="text-sm text-muted-foreground mt-3">
          Generate display ads, video clips, jingles, and voiceovers for your campaign — powered by
          Nano Banana 2, Sora, Creatomate, Suno, and ElevenLabs.
        </p>
      </div>

      <div className="px-6 py-4">
        {/* Provider status */}
        <div className="flex flex-wrap gap-2 mb-4">
          {[
            { name: 'Nano Banana 2', type: 'Images', icon: <Image className="w-3 h-3" /> },
            { name: 'Sora 2', type: 'Video', icon: <Video className="w-3 h-3" /> },
            { name: 'Creatomate', type: 'Templates', icon: <Video className="w-3 h-3" /> },
            { name: 'Suno', type: 'Jingles', icon: <Music className="w-3 h-3" /> },
            { name: 'ElevenLabs', type: 'Voice', icon: <Mic className="w-3 h-3" /> },
          ].map(p => (
            <div key={p.name} className="flex items-center gap-1.5 rounded-lg bg-muted/50 px-2.5 py-1.5 text-xs">
              {p.icon}
              <span className="font-medium">{p.name}</span>
              <span className="text-muted-foreground">({p.type})</span>
            </div>
          ))}
        </div>

        {/* Channel targets */}
        {allocatedChannels.length > 0 ? (
          <div className="text-xs text-muted-foreground mb-4">
            Generating for: {allocatedChannels.map(c => c.replace(/_/g, ' ')).join(', ')}
          </div>
        ) : (
          <div className="text-xs text-amber-600 mb-4">
            No channels allocated yet. Go back to Strategy step to set your channel mix.
          </div>
        )}

        {/* Action buttons */}
        <div className="flex gap-3 mb-4">
          <Button
            onClick={() => handleGenerate('preview')}
            disabled={isGenerating || allocatedChannels.length === 0}
            variant="outline"
            size="sm"
            className="gap-1.5"
          >
            {isGenerating ? (
              <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating...</>
            ) : (
              <><Sparkles className="w-3.5 h-3.5" /> Quick Preview</>
            )}
          </Button>
          <Button
            onClick={() => handleGenerate('full')}
            disabled={isGenerating || allocatedChannels.length === 0}
            size="sm"
            className="gap-1.5"
          >
            {isGenerating ? (
              <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating Suite...</>
            ) : (
              <><Zap className="w-3.5 h-3.5" /> Generate Full Suite</>
            )}
          </Button>
        </div>

        {/* Error display */}
        {error && (
          <div className="rounded-lg bg-red-50 border border-red-200 p-3 mb-4 text-sm text-red-700">
            {error}
          </div>
        )}

        {/* Results grid */}
        {results.length > 0 && (
          <div className="space-y-3">
            <div className="flex items-center justify-between text-sm">
              <span className="font-medium">
                {readyResults.length} asset{readyResults.length !== 1 ? 's' : ''} generated
              </span>
              {totalCost > 0 && (
                <span className="text-xs text-muted-foreground">
                  Est. cost: ${totalCost.toFixed(2)}
                </span>
              )}
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {results.map(result => {
                const iconKey = result.format.startsWith('static_') ? 'static'
                  : result.format.startsWith('video_') ? 'video'
                  : result.format
                return (
                  <div
                    key={result.id}
                    className={`rounded-xl border p-3 text-center ${
                      result.status === 'ready' ? 'border-green-200 bg-green-50/50'
                      : result.status === 'generating' ? 'border-blue-200 bg-blue-50/50'
                      : result.status === 'failed' ? 'border-red-200 bg-red-50/50'
                      : 'border-border'
                    }`}
                  >
                    <div className="flex items-center justify-center gap-1.5 mb-1">
                      {ASSET_ICONS[iconKey] || <Image className="w-3.5 h-3.5" />}
                      <span className="text-xs font-medium capitalize">
                        {result.format.replace(/_/g, ' ')}
                      </span>
                    </div>
                    <div className="text-[10px] text-muted-foreground capitalize">
                      {result.provider.replace(/_/g, ' ')}
                    </div>

                    {result.status === 'ready' && result.data && result.mime_type?.startsWith('image') && (
                      <img
                        src={`data:${result.mime_type};base64,${result.data}`}
                        alt="Generated creative"
                        className="w-full rounded-lg mt-2 border"
                      />
                    )}

                    {result.status === 'ready' && result.url && (
                      <a
                        href={result.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-primary hover:underline mt-1 block"
                      >
                        View asset
                      </a>
                    )}

                    {result.status === 'generating' && (
                      <Loader2 className="w-4 h-4 animate-spin text-blue-500 mx-auto mt-2" />
                    )}

                    {result.status === 'failed' && (
                      <span className="text-[10px] text-red-500 mt-1 block">
                        {result.error?.substring(0, 50) || 'Failed'}
                      </span>
                    )}
                  </div>
                )
              })}
            </div>

            {failedResults.length > 0 && (
              <p className="text-xs text-muted-foreground">
                {failedResults.length} asset{failedResults.length !== 1 ? 's' : ''} failed —
                check that API keys are configured in Vercel environment variables.
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
