"use client"
import { OnboardingState, SevenSins, STEP_NAMES } from '@/types/onboarding'
import { Badge } from '@/components/ui/badge'
import { FileText, Target, Users, MessageCircle, BarChart3, Zap, CheckCircle2 } from 'lucide-react'

interface Props {
  state: OnboardingState
  update: (v: Partial<OnboardingState['presentation']>) => void
}

const SIN_LABELS: Record<SevenSins, string> = {
  greed: 'Greed', pride: 'Pride', envy: 'Envy', lust: 'Desire',
  wrath: 'Frustration', sloth: 'Ease', gluttony: 'Abundance'
}

export function StepPresentation({ state }: Props) {
  const activeTriggers = state.messaging.emotional_triggers.filter(t => t.intensity > 5)
  const totalPersonas = state.personas.current.length + state.personas.ideal.length
  const allocatedChannels = Object.entries(state.strategy.budget_split).filter(([, v]) => v > 0)

  return (
    <div className="space-y-6">
      {/* Strategy document header */}
      <div className="rounded-2xl border bg-card overflow-hidden">
        <div className="bg-primary/5 border-b px-6 py-5">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center">
              <FileText className="w-5 h-5 text-primary-foreground" />
            </div>
            <div>
              <h2 className="font-bold text-lg">Strategy Brief</h2>
              <p className="text-xs text-muted-foreground">Generated by TorqueLoop AI</p>
            </div>
          </div>
          <p className="text-sm text-muted-foreground mt-2">
            Review your complete marketing strategy below. After approval, TorqueLoop will begin
            generating creatives and setting up campaigns across your chosen channels.
          </p>
        </div>

        {/* Goals section */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <Target className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Goals & Parameters</h3>
          </div>
          <div className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
            <div>
              <span className="text-muted-foreground text-xs">Primary goal</span>
              <p className="font-medium capitalize">{state.goals.primary || '—'}</p>
            </div>
            <div>
              <span className="text-muted-foreground text-xs">Timeline</span>
              <p className="font-medium">{state.goals.timeline || '—'}</p>
            </div>
            <div>
              <span className="text-muted-foreground text-xs">Budget range</span>
              <p className="font-medium">{state.goals.budget_range || '—'}</p>
            </div>
            <div>
              <span className="text-muted-foreground text-xs">Secondary goals</span>
              <p className="font-medium">
                {state.goals.secondary.length > 0
                  ? state.goals.secondary.map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(', ')
                  : '—'}
              </p>
            </div>
            <div>
              <span className="text-muted-foreground text-xs">Tracking system</span>
              <p className="font-medium capitalize">{state.tracking.system || 'None'}</p>
            </div>
            <div>
              <span className="text-muted-foreground text-xs">Connected</span>
              <p className="font-medium">{state.tracking.connected ? 'Yes' : 'Not yet'}</p>
            </div>
          </div>
        </div>

        {/* Channel history */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <BarChart3 className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Channel History</h3>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {state.channels.worked.length > 0 && state.channels.worked.map(c => (
              <Badge key={c} variant="outline" className="text-xs border-green-500/30 text-green-700 bg-green-50">
                {c} — worked
              </Badge>
            ))}
            {state.channels.failed.length > 0 && state.channels.failed.map(c => (
              <Badge key={c} variant="outline" className="text-xs border-red-500/30 text-red-700 bg-red-50">
                {c} — didn't work
              </Badge>
            ))}
            {state.channels.used.filter(c => !state.channels.worked.includes(c) && !state.channels.failed.includes(c)).map(c => (
              <Badge key={c} variant="outline" className="text-xs">
                {c} — tried
              </Badge>
            ))}
            {state.channels.used.length === 0 && (
              <span className="text-xs text-muted-foreground">No channel history provided</span>
            )}
          </div>
        </div>

        {/* Personas */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <Users className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Target Personas ({totalPersonas})</h3>
          </div>
          {totalPersonas === 0 ? (
            <span className="text-xs text-muted-foreground">No personas defined yet</span>
          ) : (
            <div className="space-y-2">
              {[...state.personas.current, ...state.personas.ideal].map((p, i) => (
                <div key={i} className="rounded-lg bg-muted/50 p-3">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-medium text-sm">{p.name || `Persona ${i + 1}`}</span>
                    <Badge variant="outline" className="text-[10px] px-1.5 py-0">{p.age_range}</Badge>
                    {p.location && <Badge variant="outline" className="text-[10px] px-1.5 py-0">{p.location}</Badge>}
                  </div>
                  {p.occupation && <div className="text-xs text-muted-foreground">{p.occupation}</div>}
                  {p.pain_points.length > 0 && (
                    <div className="text-xs mt-1">
                      <span className="text-muted-foreground">Pain points:</span>{' '}
                      {p.pain_points.join(', ')}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Messaging strategy */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <MessageCircle className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Messaging Strategy</h3>
          </div>
          <div className="mb-2">
            <span className="text-xs text-muted-foreground">Brand tone:</span>{' '}
            <span className="text-sm font-medium capitalize">{state.messaging.tone || 'Not set'}</span>
          </div>
          {activeTriggers.length > 0 ? (
            <div className="space-y-1.5">
              {activeTriggers.map(t => (
                <div key={t.sin} className="flex items-start gap-2 text-sm">
                  <Badge variant="outline" className="text-[10px] px-1.5 py-0 shrink-0 mt-0.5">
                    {SIN_LABELS[t.sin]} ({t.intensity}/10)
                  </Badge>
                  <span className="text-muted-foreground text-xs">{t.message || 'No message set'}</span>
                </div>
              ))}
            </div>
          ) : (
            <span className="text-xs text-muted-foreground">No active emotional triggers</span>
          )}
        </div>

        {/* Channel strategy */}
        <div className="px-6 py-4 border-b">
          <div className="flex items-center gap-2 mb-3">
            <Zap className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Channel Strategy</h3>
          </div>
          <div className="mb-2 text-sm">
            <span className="text-muted-foreground text-xs">Organic / Paid split:</span>{' '}
            <span className="font-medium">{state.strategy.organic_vs_paid}% organic / {100 - state.strategy.organic_vs_paid}% paid</span>
          </div>
          {allocatedChannels.length > 0 ? (
            <div className="space-y-1">
              {allocatedChannels
                .sort((a, b) => b[1] - a[1])
                .map(([ch, pct]) => (
                  <div key={ch} className="flex items-center gap-2">
                    <div className="flex-1 text-sm capitalize">{ch.replace(/_/g, ' ')}</div>
                    <div className="w-32 h-2 rounded-full bg-muted overflow-hidden">
                      <div
                        className="h-full bg-primary rounded-full transition-all"
                        style={{ width: `${pct * 2}%` }}
                      />
                    </div>
                    <span className="text-xs font-mono w-8 text-right">{pct}%</span>
                  </div>
                ))}
            </div>
          ) : (
            <span className="text-xs text-muted-foreground">No channels allocated yet</span>
          )}
        </div>

        {/* Completion checklist */}
        <div className="px-6 py-4">
          <div className="flex items-center gap-2 mb-3">
            <CheckCircle2 className="w-4 h-4 text-primary" />
            <h3 className="font-semibold text-sm">Readiness Checklist</h3>
          </div>
          <div className="space-y-1">
            {[
              { label: 'Goals defined', done: !!state.goals.primary },
              { label: 'Tracking connected', done: state.tracking.connected },
              { label: 'Channels audited', done: state.channels.used.length > 0 },
              { label: 'Personas created', done: totalPersonas > 0 },
              { label: 'Messaging crafted', done: activeTriggers.length > 0 },
              { label: 'Budget allocated', done: allocatedChannels.length > 0 },
            ].map(item => (
              <div key={item.label} className="flex items-center gap-2 text-sm">
                <div className={`w-4 h-4 rounded-full flex items-center justify-center ${
                  item.done ? 'bg-green-500 text-white' : 'bg-muted'
                }`}>
                  {item.done && <CheckCircle2 className="w-3 h-3" />}
                </div>
                <span className={item.done ? 'text-foreground' : 'text-muted-foreground'}>{item.label}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      <p className="text-xs text-muted-foreground text-center">
        In the full product, this will generate a downloadable PDF strategy brief.
      </p>
    </div>
  )
}
