// Seed proof points for Volt Studios
// These are the starting evidence library entries.
// Run via: npx tsx src/lib/proposals/seed.ts (or integrate into a Supabase seed script)

import type { ProofPoint } from '@/types/proposals'

export const SEED_PROOF_POINTS: Omit<ProofPoint, 'id'>[] = [
  {
    workspace_id: '__WORKSPACE_ID__', // replace with actual workspace UUID
    label: '29.5x ROAS — Slay the PE',
    metric: '29.5x return on ad spend',
    client_context: 'Slay the PE — professional exam prep company, paid search and social campaigns',
    problem_type: 'paid_advertising',
    service_category: 'PPC',
    best_fit: 'Companies spending on ads with unclear return; exam prep, education, or subscription businesses',
    do_not_use_when: 'Client has no existing ad spend or is pre-product',
    source_note: 'Internal campaign data',
    active: true,
  },
  {
    workspace_id: '__WORKSPACE_ID__',
    label: '93.6% CPL Reduction — Kaleo',
    metric: '93.6% reduction in cost per lead',
    client_context: 'Kaleo — lead generation overhaul across paid channels',
    problem_type: 'lead_generation',
    service_category: 'PPC',
    best_fit: 'Companies with high CPL looking to scale lead volume profitably',
    do_not_use_when: 'Client has no tracking or attribution setup',
    source_note: 'Internal campaign data',
    active: true,
  },
  {
    workspace_id: '__WORKSPACE_ID__',
    label: '220% Organic Traffic Lift',
    metric: '220% average organic traffic increase',
    client_context: 'Multiple clients — SEO and content strategy engagements',
    problem_type: 'organic_growth',
    service_category: 'SEO',
    best_fit: 'Companies with existing content but stagnant organic traffic',
    do_not_use_when: 'Client needs paid leads immediately; SEO is a long game',
    source_note: 'Aggregated across multiple engagements',
    active: true,
  },
  {
    workspace_id: '__WORKSPACE_ID__',
    label: '$4M Funding Secured — Oops Returns',
    metric: '$4M in funding secured',
    client_context: 'Oops Returns — e-commerce returns platform, brand and positioning work',
    problem_type: 'brand_positioning',
    service_category: 'Branding',
    best_fit: 'Startups seeking funding or going through a rebrand',
    do_not_use_when: 'Client is post-Series A and focused purely on performance',
    source_note: 'Client-reported outcome',
    active: true,
  },
  {
    workspace_id: '__WORKSPACE_ID__',
    label: '408% Monthly ROAS + 2 New Stores — C2Paint',
    metric: '408% monthly ROAS and 2 new physical stores opened',
    client_context: 'C2Paint — paint retailer, full-funnel digital marketing',
    problem_type: 'paid_advertising',
    service_category: 'PPC',
    best_fit: 'Retail or e-commerce brands looking to scale with measurable ad return',
    do_not_use_when: 'Client has no product-market fit yet',
    source_note: 'Internal campaign data + client confirmation',
    active: true,
  },
  {
    workspace_id: '__WORKSPACE_ID__',
    label: '9M+ Annual Users — Chkt en Linea',
    metric: '9M+ annual users',
    client_context: 'Chkt en Linea — health/wellness platform, growth and product strategy',
    problem_type: 'user_growth',
    service_category: 'Growth',
    best_fit: 'Consumer platforms or apps looking to scale user acquisition',
    do_not_use_when: 'Client is B2B with a niche TAM',
    source_note: 'Analytics data',
    active: true,
  },
  {
    workspace_id: '__WORKSPACE_ID__',
    label: '11 Years in Business — Women-Led',
    metric: '11 years in business, women-led agency',
    client_context: 'Volt Studios — agency credibility and longevity',
    problem_type: 'trust_credibility',
    service_category: 'General',
    best_fit: 'Any buyer who values stability, experience, and diverse leadership',
    do_not_use_when: '',
    source_note: 'Agency fact',
    active: true,
  },
]
